#While developing I run API locally to watch for changes
version: '3'

services:
  db:
    image: postgres:15.2
    container_name: foodPlannerDB
    networks:
      - postgres
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USERNAME}
    ports:
      - "5431:5432"
    volumes:
      - ./.postgres-data:/var/lib/postgresql/data
    restart: always

networks:
  postgres:
    driver: bridge