version: '3'

services:
  fp-db:
    image: postgres:15.2
    container_name: foodPlannerDB
    networks:
      - postgres
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USERNAME}
    ports:
      - "5431:5432"
    volumes:
      - ./.postgres-data:/var/lib/postgresql/data
    restart: always

  fp-api:
    image: danielgj78/fp-api
    container_name: foodPlannerAPI
    env_file:
      - .env-prod
    ports:
      - 8080:3000
    depends_on:
      - fp-db
    networks:
      - postgres

networks:
  postgres:
    driver: bridge