version: '3'

services:
  fp-api:
    image: danielgj78/fp-api
    container_name: foodPlannerAPI
    env_file:
      - .env-prod
    ports:
      - 8080:80
    networks:
      - postgres

networks:
  postgres:
    driver: bridge